openapi: 3.0.0
info:
  title: Environment Monitoring API
  description: 
    This Environment API is made for monitoring temperature, PM2.5, human count, and sound in the area.
  version: 2.0.0
servers:
- url: http://127.0.0.1:8080/envi-api/v2
paths:
  /latest/{param}:
    parameters:
    - name: param
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Return latest average all params from all source
      operationId: controller.latest_average
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AverageValue'
  /all/avg/{param}:
    parameters:
    - name: param
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Return all average params from all source
      operationId: controller.all_average
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AverageValue'
  /separate/{param}/{source}/hour:
    parameters:
    - name: param
      in: path
      required: true
      schema:
        type: string
    - name: source
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Return average value of specific parameters and source
      operationId: controller.hour_average_value_by_source
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HourAverageValue'
  /compare/humcount/{param}:
    parameters:
    - name: param
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Return human in the area compare with other parameters in each hours
      operationId: controller.compare_between_humcount_and_value
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CompareValue'

components:
  schemas:
    AverageValue:
      type: object
      properties:
        day:
          type: integer
        month:
          type: integer
        year:
          type: integer
        hour:
          type: integer
        value:
          type: number
    HourAverageValue:
      type: object
      properties:
        source:
          type: string
        hour:
          type: integer
        value:
          type: number
    CompareValue:
      type: object
      properties:
        year:
          type: integer
        month:
          type: integer
        day:
          type: integer
        hour:
          type: number
        humcount:
          type: number
        comparevalue:
          type: number
          description: Value of parameter that want to compare