openapi: 3.0.0
info:
  title: Environment Monitoring API
  description: 
    This API ...
  version: 2.0.0
servers:
- url: http://127.0.0.1:8080/envi-api/v2
paths:
  /latest/{param}:
    parameters:
    - name: param
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Return latest average all params from all source
      operationId: controller.latest_average
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AverageValue'
  /all/avg/{param}:
    parameters:
    - name: param
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Return all average params from all source
      operationId: controller.all_average
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AverageValue'

components:
  schemas:
    AverageValue:
      type: object
      properties:
        day:
          type: integer
        month:
          type: integer
        year:
          type: integer
        hour:
          type: integer
        value:
          type: number