openapi: 3.0.0
info:
  title: Environment Monitoring API
  description:
    This API ...
  version: 1.0.0
servers:
- url: /envi-api/v1
paths:
  /latest/temp:
    get:
      summary: Return latest average temperature from all source
      operationId: controller.latest_average_temperature
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LatestTemp'
  /lastest/pm25:
    get: 
      summary: Return latest average pm2.5 from all source
      operationId: controller.latest_average_pm25
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LatestPm25'

components:
  schemas:
    LatestTemp:
      type: object
      properties:
        day:
          type: integer
        month:
          type: integer
        year:
          type: integer
        hour:
          type: integer
        averageTemp:
          type: number
    LatestPm25:
      type: object
      properties:
        day:
          type: integer
        month:
          type: integer
        year:
          type: integer
        hour:
          type: integer
        averagePm25:
          type: number