openapi: 3.0.0
info:
  title: Environment Monitoring API
  description:
    This API provides historical rainfall data over upper Chaopraya river basin between 1987
    and 2023.  Raw data provided by Thai Meteorological Department (TMD).
  version: 2.0.0
servers:
  - url: http://127.0.0.1:8080/envi-api/v1
paths:
  /